version: "3"

services:
  puppeteer:
    build: .
    container_name: pptr
    ports:
      - "5900:5900"
    environment:
      DISPLAY: ":99"
    volumes:
      - ./data:/usr/src/app/data # Mount host's "screenshots" folder to container
